version: '3.7'
services:
  aaaxxxnginx:
    container_name: aaaxxxnginx
    image: "cr.yandex/xxxxxx/aaaxxxnginx:latest"
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - fluentbit
      - xxxxphpp
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: xxxxfront.app.logs
  xxxxphpp:
    container_name: xxxxphpp
    image: "cr.yandex/xxxxxx/xxxxphpp:latest"
    restart: always
    depends_on:
      - fluentbit
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: xxxxfront.app.logs
  fluentbit:
    container_name: fluentbit
    image: cr.yandex/yc/fluent-bit-plugin-yandex:v2.0.0-fluent-bit-1.9.0
    ports:
      - 24224:24224
      - 24224:24224/udp
    restart: always
    environment:
      YC_GROUP_ID: xxxx
      AWS_CONFIG_FILE: /home/.aws/config
      AWS_SHARED_CREDENTIALS_FILE: /home/.aws/credentials
    volumes:
      - /etc/fluent-bit:/fluent-bit/etc
      - /var/log/fluentbit:/var/log/fluentbit
      - /home/.aws:/home/.aws
